version: '3.9'

services:

  db:
    image: postgres:16.3
    container_name: postgres-artisan
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: artisanconnect_auth
      DB_HOST: postgres-artisan

    networks:
      - app-networks
    ports:
      - "5435:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    networks: 
      - app-networks
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db
    command: [ "-path", "/migrations", "-database", "postgres://postgres:pass@postgres-artisan:5432/artisanconnect_auth?sslmode=disable", "up" ]


  auth-service:
    build: .
    container_name: auth-service
    networks:
      - app-networks
    ports:
      - "8075:8075"
    depends_on:
      - db

volumes:
  db-data: 

networks:
  app-networks:
    name: app-networks
    external: true
